### ISSUE TITLE
NOTEs when running check 

### ISSUE THREAD

**Issue by hurielreichel** [hurielreichel/tidyopeneo#6]
❯ checking for future file timestamps ... NOTE
  unable to verify current time

❯ checking R code for possible problems ... [12s/10s] NOTE
  filter.datacube: no visible binding for global variable ‘.’
  Undefined global functions or variables:
    .

**Comment by hurielreichel** [comment]
The first seems random, as only shows up some times. More than that, it's not really relevant, I guess. 
The second, I don't find the issue, but it is certainly in filter.datacube and has been introduced with 55df98773c7834b6c41537e9a54847dddc0428e9

@edzer Can you see if you can reproduce?

**Comment by edzer** [comment]
Line 245:
```
        date2 = date2 %>% format(., "%04Y-%m-%d")
```

**Comment by hurielreichel** [comment]
As always... sharp!
